import type { Content } from "./content";

export const defaultContent: Content = {
  announcement: {
    enabled: true,
    items: [
      "🛂 Free Eligibility Check",
      "☎️ +92 314 535 2222",
      "📍 F-11 Markaz, Islamabad",
      "🏆 Pakistan's No. 1 Trusted Name in Genuine Visa Processing",
      "✅ 100% Authentic Process · No Hidden Fees",
      "🌍 UK · USA · Canada · Australia · Turkey · Schengen",
    ],
  },
  hero: {
    preHeadline: "✦ 18 Years · Licensed · Islamabad ✦",
    headlineWords: ["A", "Step", "Before"],
    headlineAccent: "Embassy.",
    subhead:
      "Premium visa consultancy for UK · USA · Canada · Australia · Turkey · Schengen. Real eligibility checks. Embassy-grade documentation. No hidden fees — ever.",
    ctaPrimary: "Free Eligibility Check",
    ctaPrimaryLink: "/eligibility",
    ctaSecondary: "Talk on WhatsApp",
    ctaSecondaryLink: "https://wa.me/923145352222",
    trustStrip: [
      "🛡️ Licensed Consultants",
      "⭐ 4.9/5 · 500+ reviews",
      "✅ 99% Success Rate",
      "🗓️ Since 2007",
    ],
  },
  trustBadges: [
    { icon: "🛡️", title: "Licensed", sub: "Verified travel & consultancy" },
    { icon: "🏛️", title: "Embassy-Grade", sub: "Files built to policy" },
    { icon: "💎", title: "18 Years", sub: "Since 2007" },
    { icon: "🔒", title: "No Hidden Fees", sub: "Transparent pricing" },
    { icon: "⚡", title: "Fast Processing", sub: "Priority handling" },
    { icon: "🌍", title: "50+ Countries", sub: "Global expertise" },
  ],
  stats: [
    { value: 18, suffix: "+", label: "Years of Excellence" },
    { value: 5000, suffix: "+", label: "Visas Processed" },
    { value: 99, suffix: "%", label: "Success Rate" },
    { value: 50, suffix: "+", label: "Countries Covered" },
  ],
  countries: [
    {
      slug: "uk",
      name: "United Kingdom",
      flag: "🇬🇧",
      lat: 51.5,
      lng: -0.12,
      processing: "15–20 working days",
      success: "98%",
      visaTypes: ["Standard Visitor", "Business", "Family Visit", "Medical"],
      blurb:
        "Standard Visitor visas filed with full financial narrative and travel-history framing that UKVI caseworkers expect.",
      gradient: "from-[#1e3a8a] to-[#7f1d1d]",
      eligibility: [
        "Genuine visit purpose with clear return intent",
        "Stable income or business in Pakistan",
        "6-month bank statement supporting trip cost",
        "Clean immigration history preferred",
      ],
      documents: [
        "Valid passport (6+ months)",
        "CNIC & FRC",
        "Bank statements (6 months)",
        "Employment / business proof",
        "Property documents (if any)",
        "Invitation letter (if visiting family)",
      ],
      faqs: [
        {
          q: "How long is a UK visitor visa valid?",
          a: "Standard Visitor visas are typically issued for 6 months, with 2, 5 and 10-year multi-entry options for strong profiles.",
        },
        {
          q: "Does a previous refusal end my chances?",
          a: "No. We analyse the refusal letter, fix the exact weaknesses, and re-file with a corrected narrative. Many of our approvals are post-refusal cases.",
        },
      ],
    },
    {
      slug: "usa",
      name: "United States",
      flag: "🇺🇸",
      lat: 38.9,
      lng: -77.03,
      processing: "Interview-based (B1/B2)",
      success: "96%",
      visaTypes: ["B1/B2 Visit", "Business", "Family Visit"],
      blurb:
        "Complete DS-160 filing, embassy selection (Islamabad/Karachi), and one-on-one interview preparation.",
      gradient: "from-[#1e3a8a] to-[#b91c1c]",
      eligibility: [
        "Strong ties to Pakistan (job, family, property)",
        "Clear travel purpose and itinerary",
        "Financial capacity for the trip",
        "Confident, consistent interview answers",
      ],
      documents: [
        "Valid passport",
        "CNIC & FRC",
        "DS-160 confirmation",
        "Bank statements",
        "Employment / business proof",
        "Previous visas & travel history",
      ],
      faqs: [
        {
          q: "Do you prepare me for the interview?",
          a: "Yes — mock interviews covering the exact question patterns used at the Islamabad and Karachi posts, until your answers are natural and consistent.",
        },
        {
          q: "Which embassy should I choose?",
          a: "We select Islamabad or Karachi based on appointment availability and your profile. This is handled during DS-160 filing.",
        },
      ],
    },
    {
      slug: "canada",
      name: "Canada",
      flag: "🇨🇦",
      lat: 45.42,
      lng: -75.7,
      processing: "30–60 days",
      success: "97%",
      visaTypes: ["Visitor Visa (TRV)", "Super Visa", "Business", "Family Visit"],
      blurb:
        "IRCC-compliant applications with purpose-of-travel letters and financial documentation structured the way visa officers read them.",
      gradient: "from-[#b91c1c] to-[#7f1d1d]",
      eligibility: [
        "Proof of funds for full stay",
        "Strong home ties and return intent",
        "Host/invitation details (if applicable)",
        "Travel history strengthens the file",
      ],
      documents: [
        "Valid passport",
        "CNIC & FRC",
        "Bank statements (6 months)",
        "Income / business proof",
        "Invitation & host status in Canada (if any)",
        "Property documents (if any)",
      ],
      faqs: [
        {
          q: "What is a Super Visa?",
          a: "A multi-entry visa for parents/grandparents of Canadian citizens or PRs — valid up to 10 years with stays of up to 5 years per entry. We handle the insurance and income-threshold requirements.",
        },
        {
          q: "Is biometric required?",
          a: "Yes, biometrics are given at the VFS centre after submission. We book and guide the appointment.",
        },
      ],
    },
    {
      slug: "australia",
      name: "Australia",
      flag: "🇦🇺",
      lat: -35.28,
      lng: 149.13,
      processing: "20–35 days",
      success: "97%",
      visaTypes: ["Visitor (600)", "Business Stream", "Family Sponsored"],
      blurb:
        "Subclass 600 applications with genuine-visitor evidence built to Home Affairs decision-ready standard.",
      gradient: "from-[#0f766e] to-[#1e3a8a]",
      eligibility: [
        "Genuine temporary entrant evidence",
        "Financial capacity for stay",
        "Health & character requirements",
        "Sponsor documents (family stream)",
      ],
      documents: [
        "Valid passport",
        "CNIC & FRC",
        "Bank statements",
        "Employment / business evidence",
        "Sponsor documents (if family stream)",
        "Travel itinerary",
      ],
      faqs: [
        {
          q: "Is the Australian visa online?",
          a: "Yes — subclass 600 is lodged through ImmiAccount. We prepare, lodge and track the entire application for you.",
        },
        {
          q: "How long can I stay?",
          a: "Grants are typically 3, 6 or 12 months per stay depending on your purpose and profile strength.",
        },
      ],
    },
    {
      slug: "schengen",
      name: "Schengen States",
      flag: "🇪🇺",
      lat: 48.85,
      lng: 2.35,
      processing: "15–30 days",
      success: "98%",
      visaTypes: ["Tourist", "Business", "Family Visit", "Medical", "Events"],
      blurb:
        "One visa, 29 European countries. We select the right embassy for your itinerary and build a refusal-proof file.",
      gradient: "from-[#1e40af] to-[#facc15]",
      eligibility: [
        "Confirmed itinerary & accommodation",
        "Schengen-compliant travel insurance",
        "Financial means for full trip",
        "Return ties in Pakistan",
      ],
      documents: [
        "Valid passport",
        "CNIC & FRC",
        "Bank statements (6 months)",
        "Travel insurance (we arrange)",
        "Flight & hotel reservations (we arrange)",
        "Employment / business proof",
      ],
      faqs: [
        {
          q: "Which country should I apply through?",
          a: "The country of main destination (longest stay) — or first entry if stays are equal. We plan the itinerary so your file goes to the most suitable consulate.",
        },
        {
          q: "Is insurance mandatory?",
          a: "Yes — minimum €30,000 medical coverage across all Schengen states. We issue embassy-approved policies in-house.",
        },
      ],
    },
    {
      slug: "turkey",
      name: "Turkey",
      flag: "🇹🇷",
      lat: 39.93,
      lng: 32.86,
      processing: "7–15 days",
      success: "99%",
      visaTypes: ["Tourist (Sticker)", "E-Visa (eligible holders)", "Business"],
      blurb:
        "Fast-track Turkish sticker visas and complete Istanbul/Cappadocia tour packages under one roof.",
      gradient: "from-[#b91c1c] to-[#0f172a]",
      eligibility: [
        "Valid passport & clean record",
        "Trip funding proof",
        "Hotel & flight bookings",
        "E-visa route if holding valid US/UK/Schengen visa",
      ],
      documents: [
        "Valid passport",
        "CNIC",
        "Bank statement (3–6 months)",
        "Hotel & flight reservations",
        "Employment / business proof",
      ],
      faqs: [
        {
          q: "Can Pakistanis get a Turkish e-visa?",
          a: "Only if you hold a valid Schengen, UK, US or Irish visa/residence. Otherwise a sticker visa is filed through the gateway — we handle both routes.",
        },
        {
          q: "Do you also arrange the tour?",
          a: "Yes — visa + flights + hotels + guided Istanbul/Cappadocia tours as one package.",
        },
      ],
    },
  ],
  services: [
    { slug: "air-ticketing", icon: "✈️", title: "Air Ticketing", desc: "Best international & domestic fares across 200+ destinations with instant confirmation." },
    { slug: "hotel-booking", icon: "🏨", title: "Hotel Booking", desc: "Verified hotels worldwide — embassy-acceptable booking confirmations included." },
    { slug: "travel-insurance", icon: "🛡️", title: "Travel Insurance", desc: "Schengen-approved coverage that meets every embassy's minimum requirement." },
    { slug: "tours", icon: "🗺️", title: "Travel & Tours", desc: "Curated Europe, Turkey, Umrah and Asia packages — fully managed end to end." },
  ],
  processSteps: [
    { n: "01", title: "Free Eligibility Check", desc: "Share your basic profile. We assess it against real embassy policies — honestly, before you spend a rupee." },
    { n: "02", title: "Document Preparation", desc: "Every document guided and reviewed to embassy-grade standard. No gaps, no guesswork." },
    { n: "03", title: "Application Filing", desc: "Appointment booked, forms filed, file submitted — tracked and updated at every stage." },
    { n: "04", title: "Visa Stamped", desc: "Collect your passport, book your flight. Ticketing, hotels and insurance handled in-house." },
  ],
  tours: [
    { slug: "turkey-istanbul-cappadocia", title: "Turkey — Istanbul & Cappadocia", days: 7, nights: 6, price: "PKR 285,000", old: "PKR 325,000", tag: "Best Seller", includes: ["Visa", "Flights", "4★ Hotels", "Bosphorus Cruise", "Balloon Ride*"], emoji: "🎈", gradient: "from-rose-900/70 to-sapphire-900" },
    { slug: "europe-grand-tour", title: "Europe Grand Tour — 4 Countries", days: 12, nights: 11, price: "PKR 695,000", old: null, tag: "Premium", includes: ["Schengen Visa", "Flights", "Hotels", "Paris · Rome · Swiss · Amsterdam"], emoji: "🗼", gradient: "from-indigo-900/70 to-sapphire-900" },
    { slug: "umrah-premium", title: "Umrah Premium Package", days: 14, nights: 13, price: "PKR 385,000", old: "PKR 420,000", tag: "Spiritual", includes: ["Visa", "Flights", "Hotels near Haram", "Transport", "Ziyarat"], emoji: "🕋", gradient: "from-emerald-900/70 to-sapphire-900" },
    { slug: "baku-azerbaijan", title: "Baku, Azerbaijan Getaway", days: 5, nights: 4, price: "PKR 195,000", old: null, tag: "Quick Escape", includes: ["E-Visa", "Flights", "4★ Hotel", "City Tour", "Gabala Day Trip"], emoji: "🔥", gradient: "from-amber-900/70 to-sapphire-900" },
  ],
  testimonials: [
    { name: "Ahmed R.", country: "🇬🇧 UK Visitor Visa", text: "After one refusal elsewhere, Mustafa sb rebuilt my file from zero. Visa approved in 18 days. The difference was the documentation quality.", rating: 5 },
    { name: "Sana & Family", country: "🇨🇦 Canada Super Visa", text: "Parents' Super Visa approved — insurance, income letters, everything handled in one office. Zero running around.", rating: 5 },
    { name: "Bilal K.", country: "🇪🇺 Schengen (France)", text: "They planned my whole itinerary so the file went to the right consulate. Insurance and bookings were done in-house same day.", rating: 5 },
    { name: "Dr. Hira M.", country: "🇺🇸 USA B1/B2", text: "The mock interviews were the game-changer. Walked into the embassy knowing every question before it was asked.", rating: 5 },
    { name: "Usman T.", country: "🇹🇷 Turkey + Tour", text: "Visa, flights, hotels, balloon ride — one payment, one WhatsApp group, zero stress. This is how travel should work.", rating: 5 },
    { name: "Farhan A.", country: "🇦🇺 Australia 600", text: "Honest assessment first — they told me exactly what to fix in my bank statements before filing. Approved first attempt.", rating: 5 },
  ],
  videos: [
    { id: "v1", title: "How to Prepare for a Schengen Visa Interview", youtubeId: "dQw4w9WgXcQ", category: "Knowledge" },
    { id: "v2", title: "UK Visitor Visa — Required Documents Checklist", youtubeId: "dQw4w9WgXcQ", category: "Knowledge" },
    { id: "v3", title: "Turkey Tour Highlights — Istanbul & Cappadocia", youtubeId: "dQw4w9WgXcQ", category: "Tours" },
    { id: "v4", title: "Canada Super Visa Explained", youtubeId: "dQw4w9WgXcQ", category: "Knowledge" },
    { id: "v5", title: "Europe Grand Tour — Client Journey", youtubeId: "dQw4w9WgXcQ", category: "Tours" },
    { id: "v6", title: "USA B1/B2 Interview Preparation Tips", youtubeId: "dQw4w9WgXcQ", category: "Knowledge" },
  ],
  gallery: [
    { id: "g1", url: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80", caption: "Paris, France", category: "Tours" },
    { id: "g2", url: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&q=80", caption: "Istanbul, Turkey", category: "Tours" },
    { id: "g3", url: "https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&q=80", caption: "Makkah, Saudi Arabia", category: "Umrah" },
    { id: "g4", url: "https://images.unsplash.com/photo-1543832923-44667a44c804?w=1200&q=80", caption: "Cappadocia Balloons", category: "Tours" },
    { id: "g5", url: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=80", caption: "London, United Kingdom", category: "Tours" },
    { id: "g6", url: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1200&q=80", caption: "Rome, Italy", category: "Tours" },
    { id: "g7", url: "https://images.unsplash.com/photo-1493707553966-283afac8c358?w=1200&q=80", caption: "Baku, Azerbaijan", category: "Tours" },
    { id: "g8", url: "https://images.unsplash.com/photo-1490642914619-7955a3fd483c?w=1200&q=80", caption: "Sydney, Australia", category: "Tours" },
  ],
  ceo: {
    name: "S. Mustafa",
    role: "Founder & CEO · New Euro Consultants",
    photo: "",
    tagline: "Pakistan's No. 1 Trusted Name in Genuine Visa Processing",
    bio:
      "S. Mustafa is the Founder and CEO of New Euro Consultants — one of Islamabad's most trusted names in visa processing and international travel. Over more than a decade, he has personally guided thousands of Pakistani applicants through the UK, USA, Canada, Australia, Turkey and the Schengen states — with a reputation built on transparency, embassy-grade documentation, and a strict no-hidden-fees policy.",
    since: 2011,
    highlights: [
      "Visa Consultant · International Group Tours Organiser",
      "Travel & Tours Services professional",
      "Humanitarian & philanthropist",
      "Motivational speaker & event organiser",
      "Trusted advisor to thousands of successful applicants",
      "Personally travels across Pakistan to meet clients",
    ],
    quote:
      "We are a step before Embassy. If your profile isn't ready, we'll tell you honestly — that transparency is the entire reason our clients trust us.",
    reachInstagram: "192K+",
    reachFacebook: "125K+",
    socials: {
      instagram: "https://www.instagram.com/worldofmustafa1/",
      facebook: "https://www.facebook.com/worldofmustafa1/",
      tiktok: "https://www.tiktok.com/@worldofmustafa",
      youtube: "https://www.youtube.com/c/WorldofMustafa",
    },
  },
  customSections: [
    {
      id: "cs-authenticity",
      enabled: true,
      title: "100% Authentic Visa Process",
      subtitle: "No shortcuts. No fake documents. No hidden fees.",
      body:
        "Every file we submit to an embassy is built exactly the way that embassy expects it — genuine documentation, honest declarations, and a case narrative that stands up to scrutiny. That is why our approval rate stays where it is, and why refusal cases from other consultants become approvals with us.",
      ctaText: "Talk to Us",
      ctaLink: "/contact",
      layout: "centered",
      accent: "gold",
    },
  ],
  faqs: [
    { q: "Is the eligibility check really free?", a: "Yes. We assess your documents against actual embassy policies before you commit to anything. If your profile isn't ready, we tell you honestly what to fix and when to apply — that's the meaning of 'a step before Embassy'." },
    { q: "What documents do I need to bring?", a: "Passport, CNIC, FRC, source-of-income proof, 6-month bank statements, property documents (if any), and your family circumstances. Bring what you have — we'll map the gaps." },
    { q: "I was refused before. Can you still help?", a: "Refusal cases are our specialty. We read the refusal letter line by line, fix the exact weaknesses, and re-file with corrected evidence. A refusal is a diagnosis, not a dead end." },
    { q: "Do you guarantee a visa?", a: "No honest consultant can — the decision belongs to the embassy. What we guarantee is an embassy-grade file, transparent assessment, and no hidden fees. Our 18-year track record speaks for the rest." },
    { q: "Do you handle flights, hotels and insurance too?", a: "Yes — air ticketing, embassy-acceptable hotel confirmations, and Schengen-approved travel insurance are all issued in-house. One office, complete travel." },
    { q: "Where is your office?", a: "Office 17-18, 1st Floor, Lord Trade Centre, F-11 Markaz, Islamabad (near Najeeb Pharmacy). Monday–Friday, 9 AM–4 PM. Walk-ins welcome, WhatsApp preferred for appointments." },
  ],
  contact: {
    fullName: "New Euro Consultants Travel & Tours",
    tagline: "A Step Before Embassy",
    since: 2007,
    years: "18+",
    phone: "+92 314 535 2222",
    phoneRaw: "923145352222",
    whatsapp: "923145352222",
    email: "info@neweuroconsultants.com",
    address: "Office No. 17-18, 1st Floor, Lord Trade Centre, F-11 Markaz, Islamabad",
    hours: "Mon – Fri · 9:00 AM – 4:00 PM",
    mapsUrl: "https://maps.app.goo.gl/VtsZB1DP8oL6PQm38",
    mapsEmbed: "https://www.google.com/maps?q=New+Euro+Consultants,+Lord+Trade+Centre,+Office+17-18,+F-11+Markaz,+Islamabad&t=&z=17&ie=UTF8&iwloc=B&output=embed",
    coords: { lat: 33.68414, lng: 72.99936 },
    social: {
      instagram: "https://www.instagram.com/neweuroconsultants/",
      tiktok: "https://www.tiktok.com/@worldofmustafa",
      facebook: "https://www.facebook.com/worldofmustafa",
      youtube: "https://www.youtube.com/@neweuroconsultants",
    },
    requiredDocs: [
      "Passport",
      "CNIC",
      "FRC (Family Registration Certificate)",
      "Source of income proof",
      "Bank statements (6 months)",
      "Property documents (if any)",
      "Family circumstances detail",
    ],
  },
};
